#Nepal

#-----------------------------------------------------------------------------------------------

country = {
	tag = NEP
	ai = "SmallTrade0.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 150
	inflation = 0
	merchants = 0
	religion = { type = hindu }
	culture = { type = nepali }
	diplomacy = { }
	knownprovinces = {
		543 544 545 553 554 555 556 557 558 559 560 561 562 671 672 1074 1078 1389 1520 1521 1523
		1539 1540 1541 1542 1543 1544 1545 1546 1547 1548 1557 1558 1559 1604 1605 1606 1607 1608
	}
	ownedprovinces = {
		1539
	}
	controlledprovinces = {
		1539
	}
	nationalprovinces = {
		1539
	}
	city = {
		fortress = { level = 2 }
		population = 8000
		location = 1539
		bailiff = yes
		courthouse = yes
		cityrights = yes
		capital = yes
	}
	landunit = {
		id = { type = 9423 id = 848 }
		name = "Nepali Army"
		location = 1539
		infantry = 6000
		cavalry = 0
		artillery = 10
	}
	technology = {
		stability = { level = 2 value = 42 }
		infra = { level = 4 value = 700 }
		trade = { level = 3 value = 2500 }
		land = { level = 20 value = 50 }
		naval = { level = 3 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
