#Ajuuraan/Hobyo

#-----------------------------------------------------------------------------------------------

country = {
	tag = AJU
	policy = {
		aristocracy = 5
		centralization = 6
		innovative = 4
		mercantilism = 5
		offensive = 7
		land = 3
		quality = 6
		serfdom = 10
	}
	ai = "SmallTrade1.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0
	religion = { type = sunni }
	culture = {
		type = somali
		type = arabic
	}
	diplomacy = {
		relation = { tag = TUR value = 100 refusetrade = no }
		relation = { tag = MLI value = 100 refusetrade = no }
		relation = { tag = KIL value = 100 refusetrade = no }
		relation = { tag = ZAN value = 100 refusetrade = no }
		relation = { tag = ADA value = -50 refusetrade = no }
		relation = { tag = ETH value = -80 refusetrade = no }
		relation = { tag = POR value = -100 refusetrade = no }
	}
	knownprovinces = {
		357 441 489 494 495 496 497 498 499 500 501 502 503 504 505 506 507 508 509 532 533 534 536 
		537 538 539 541 547 746 747 748 749 750 751 752 753 754 755 756 757 758 759 760 761 762 763 764 765 766 767 768 769 
		770 1059 1060 1061 1062 1063 1064 1065 1066 1067 1068 1069 1070 1071 1133 1134 1135 
		1136 1138 1184 1185 1186 1359 1363 1512 1513 1514 1515 1516 1517 1518 1519 1589 1590 1592 
	}
	ownedprovinces = {
		757 758 759 760
	}
	controlledprovinces = {
		757 758 759 760
	}
	nationalprovinces = {
		757 758 759 760
	}
	city = {
		fortress = { level = 1 }
		population = 5000
		location = 757
		bailiff = yes
		courthouse = yes
	}
	city = {
		fortress = { level = 1 }
		population = 3500
		location = 758
		bailiff = yes
		courthouse = yes
	}
	city = {
		fortress = { level = 1 }
		population = 8000
		location = 759
		capital = yes
		bailiff = yes
		courthouse = yes
	}
	city = {
		fortress = { level = 1 }
		population = 12000
		location = 760
		bailiff = yes
		courthouse = yes
	}
	technology = {
		stability = { level = 0 value = 42 }
		infra = { level = 4 value = 10 }
		trade = { level = 4 value = 70 }
		land = { level = 15 value = 50 }
		naval = { level = 14 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
