#Ajuuraan/Hobyo

#-----------------------------------------------------------------------------------------------

country = {
	tag = AJU
	policy = {
		aristocracy = 7
		centralization = 5
		innovative = 4
		mercantilism = 7
		offensive = 6
		land = 3
		quality = 4
		serfdom = 10
	}
	ai = "SmallTrade1.txt"
	colonialattempts = 0
	colonialnation = no
	major = no
	colonists = 0
	cancelledloans = 0
	extendedloans = 0
	treasury = 200
	inflation = 0
	merchants = 0
	religion = { type = sunni }
	culture = {
		type = somali
		type = arabic
	}
	diplomacy = {
		relation = { tag = ADA value = -25 refusetrade = no }
		relation = { tag = MGU value = 50 refusetrade = no }
	}
	knownprovinces = {
		357 494 495 496 497 498 499 500 501 502 503 746 747 748 749 750 751 752 753 754 755 756 757 758 759 760 761 762 763 764 765 766 767 1516 1517 1518 1519 1590
		1059 1060 1061 1062 1064 1133 1134 1135 1185 1186
	}
	ownedprovinces = {
		757 758 759
	}
	controlledprovinces = {
		757 758 759
	}
	nationalprovinces = {
		757 758 759
	}
	city = {
		fortress = { level = 1 }
		population = 2000
		location = 757
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 1500
		location = 758
		bailiff = yes
	}
	city = {
		fortress = { level = 1 }
		population = 6000
		location = 759
		capital = yes
		bailiff = yes
	}
	technology = {
		stability = { level = -1 value = 42 }
		infra = { level = 1 value = 10 }
		trade = { level = 1 value = 70 }
		land = { level = 4 value = 50 }
		naval = { level = 2 value = 0 }
	}
}

#-----------------------------------------------------------------------------------------------
